### ISSUE TITLE
It never had to be in discord, github has mentioning

### ISSUE THREAD

**Issue by sandstripes** [Voxalice/hello-world#1]
@Voxalice 
![E01305AC-F1C8-466D-BF47-93D00714E6B2](https://user-images.githubusercontent.com/89811520/164893048-b118d840-9a43-4b2c-a4d8-8f6599154df0.png)

**Comment by tnix100** [comment]
@catonmeower

**Comment by Voxalice** [comment]
@catonmeower @tnix100 
banned from repo ;)
